version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: sarkari-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - sarkari-network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: sarkari-server-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mongodb
    volumes:
      - ./server/uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - sarkari-network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: sarkari-client-prod
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - sarkari-network

  nginx:
    image: nginx:alpine
    container_name: sarkari-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - client
      - server
    networks:
      - sarkari-network

volumes:
  mongodb_data:

networks:
  sarkari-network:
    driver: bridge
